<section class="hr_panel hr_mzdovy_prehled">
    <?php if ($mzdovyError !== ''): ?>
        <p class="hr_notice hr_error"><?= h($mzdovyError) ?></p>
    <?php else: ?>
        <div class="hr_table_wrap">
            <table class="hr_table hr_mzdovy_table">
                <thead>
                    <tr class="hr_mzdovy_group_row"><th class="hr_table_cell" colspan="8">Základní informace</th><th class="hr_table_cell" colspan="2">Příplatky SP a ošatné</th><th class="hr_table_cell" colspan="5">Počet odpracovaných hodin</th><th class="hr_table_cell" colspan="3">Dovolená</th><th class="hr_table_cell" colspan="4">Příplatky Kč</th><th class="hr_table_cell" colspan="3">Bonusová složka</th><th class="hr_table_cell" colspan="2">Přesčasy</th><th class="hr_table_cell" colspan="2">Celková mzda</th><th class="hr_table_cell">Odvody</th></tr>
                    <tr><th class="hr_table_cell hr_table_head">ID</th><th class="hr_table_cell hr_table_head">Jméno</th><th class="hr_table_cell hr_table_head">Příjmení</th><th class="hr_table_cell hr_table_head">Pobočka</th><th class="hr_table_cell hr_table_head">Pozice</th><th class="hr_table_cell hr_table_head">Typ úvazku</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Mzda</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Průměrný výdělek za h.</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Ošatné</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Stravenkový paušál</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Celkem</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Noční</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Svátek</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Svátek noc</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Víkend</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Poč. stav</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Čerpáno</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Zůstatek</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Noc Kč</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Svátek Kč</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Svátek noc Kč</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Víkend Kč</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Bonus ISK %</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Bonus ISK Kč</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Bonus tržba</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Přesčas h</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Přesčas Kč</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Hrubá mzda</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">Čistá mzda</th><th class="hr_table_cell hr_table_head hr_mzdovy_num">ZSP</th></tr>
                </thead>
                <tbody>
                    <?php if ($mzdovyPrehled['rows'] === []): ?>
                        <tr><td class="hr_table_cell hr_employee_list_empty" colspan="30">Pro zvolené období nejsou k dispozici žádní zaměstnanci.</td></tr>
                    <?php else: ?>
                        <?php foreach ($mzdovyPrehled['rows'] as $row): ?>
                            <tr><td class="hr_table_cell"><?= h((string)(int)$row['id_person']) ?></td><td class="hr_table_cell"><a class="hr_table_link" href="<?= h(cb_root_url('index.php?m=hr&page=zamestnanec&id=' . rawurlencode((string)(int)$row['id_person']))) ?>"><?= h((string)($row['jmeno'] ?? '')) ?></a></td><td class="hr_table_cell"><?= h((string)($row['prijmeni'] ?? '')) ?></td><td class="hr_table_cell"><?= h((string)($row['pobocka'] ?? '')) ?></td><td class="hr_table_cell"><?= h((string)($row['zarazeni'] ?? '')) ?></td><td class="hr_table_cell"><?= h((string)($row['pracovni_vztah'] ?? '')) ?><?= $row['uvazek'] === null ? '' : ' ' . h(cb_format('n', (float)$row['uvazek'])) ?></td><td class="hr_table_cell hr_mzdovy_num"><?= $row['mzda_castka'] === null ? '' : h(cb_format('p', (float)$row['mzda_castka'])) ?></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"><?= h(cb_format('n', (float)$row['odpracovano'])) ?></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td><td class="hr_table_cell hr_mzdovy_num"></td></tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
                <tfoot><tr class="hr_mzdovy_total_row"><td class="hr_table_cell" colspan="10">Celkem</td><td class="hr_table_cell hr_mzdovy_num"><?= h(cb_format('n', (float)$mzdovyPrehled['total_hours'])) ?></td><td class="hr_table_cell" colspan="19"></td></tr></tfoot>
            </table>
        </div>
    <?php endif; ?>
</section>
